# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            "CPIHTC"
tagline:          'CPI High Tech Club'
description:      'Working on bringing the tech skill gap and real world problem solving closer together, locally at CPI, Cumilla.'
url:              https://cpihtc.github.io
baseurl:          ''

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

author:
  name: 'cpihtc'
  url: https://github.com/cpihtc
  twitter: "cpihtc"


# For a global message in the head
message:

exclude: []
